name: run-tests

on: [push]

jobs:

  run-api-tests:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      PORT: 3000

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Read node version from .nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
